### ISSUE TITLE
Upgrade to .NET 5?

### ISSUE THREAD

**Issue by christophwille** [zxyao145/BQuery#1]
Would you consider upgrading the library for .NET 5 Blazor? (eg Blazorise also just left < 5.0 behind)

**Comment by zxyao145** [comment]
OK, thank you! And I'll do it this weekend.

**Comment by christophwille** [comment]
I am doing a local quick test - \BQuery.Sample\Pages\FocusAndDragable.razor - input.FocusAsync in line 17 is now "error CS0121: The call is ambiguous between the following methods or properties: 'Microsoft.AspNetCore.Components.ElementReferenceExtensions.FocusAsync(Microsoft.AspNetCore.Components.ElementReference)' and 'BQuery.Bq.FocusAsync(Microsoft.AspNetCore.Components.ElementReference)'" because Blazor can focus input elements now.

Other than that I basically had only to massage the sample project by way of https://www.davideguida.com/how-to-migrate-blazor-webassembly-to-net-5/

**Comment by zxyao145** [comment]
It has been upgraded to. NET 5.
