### ISSUE TITLE
Question on "Async"

### ISSUE THREAD

**Issue by christophwille** [zxyao145/BQuery#3]
Are you targeting both Server and Web Assembly, or only Web Assembly? Reason for asking is that the Async wouldn't be strictly necessary, eg I am using `builder.Services.AddSingleton(serviceProvider => (IJSInProcessRuntime)serviceProvider.GetRequiredService<IJSRuntime>());` to avoid having to do async calls in my Web Assembly project (note that this injection is intended for pages).

**Comment by zxyao145** [comment]
It is targeting both Server and Web Assembly.

**Comment by christophwille** [comment]
Thanks, so Async is necessary.
