### ISSUE TITLE
Upgrade to .NET 6.0

### ISSUE THREAD

**Issue by christophwille** [zxyao145/BQuery#9]
Given that 5.0 will EOL in May, simply replace the 5.0 target with 6.0

**Comment by zxyao145** [comment]
Thanks alot, I will upgrade this weekend!

**Comment by zxyao145** [comment]
BQuery v3 has been published, and It supports .NET 6

**Comment by christophwille** [comment]
Great, thanks!

**Comment by zxyao145** [comment]
It's my pleasure.
